### ISSUE TITLE
Configure master branch like gh-pages (GitHub Pages "publishing source")

### ISSUE THREAD

**Issue by danielweck** [ffoodd/Talks#4]
Go to "settings", and select the `master` branch as the "publishing source" for GitHub Pages. You will then be able to access the HTML slides directly, for example:
https://github.com/ffoodd/Talks/blob/master/paris-web.2018/index.html
=>
https://ffoodd.github.io/Talks/paris-web.2018/index.html
:)

**Comment by danielweck** [comment]
Because RawGit is dead, this works:
https://rawcdn.githack.com/ffoodd/Talks/master/paris-web.2018/index.html
or:
https://cdn.staticaly.com/gh/ffoodd/Talks/master/paris-web.2018/index.html

**Comment by danielweck** [comment]
Related issue: https://github.com/ffoodd/a11y.css/issues/333

**Comment by ffoodd** [comment]
FYI, this is only a repository: slides are published on my own domain, [ffoodd.fr](https://www.ffoodd.fr).
Also there is no occurrence of rawgit anywhere in my slides :)

Thanks for the idea though, might be useful someday!
